### ISSUE TITLE
TTM demo not working

### ISSUE THREAD

**Issue by DHG-Dav** [asigalov61/Euterpe-X#3]
![image](https://github.com/asigalov61/Euterpe-X/assets/95366910/a8fe9695-87b9-42ee-bef5-24276dd88d08)
Wanted to try your model, all settings are default outside title/artist, i join the screen of the error.

**Comment by asigalov61** [comment]
@DHG-Dav Thank you very much for reporting this. I corrected the code/colab. There was a conflict between xtransformer module and random module.

Now everything should work fine. But please let me know if it doesn't :)

Alex.
