### ISSUE TITLE
MPS Support?

### ISSUE THREAD

**Issue by fakerybakery** [asigalov61/Euterpe-X#6]
Hi, might it be possible to add Apple Silicon/MPS support? Thanks!

**Comment by asigalov61** [comment]
@fakerybakery I do not have access to mac systems/hardware so I do not think I can add the support for Apple at the moment. Sorry.

But I check here:
https://developer.apple.com/metal/pytorch/

And it seems it is very easy to do with my implementations. It seems to be the matter of changing the device type and map location of the model.

**Comment by asigalov61** [comment]
@fakerybakery I am closing this issue for now. But feel free to re-open it if you need to. I may be able to assist you with mac stuff but not much tbh.

Also, please check out my upcoming SOTA model which will feature full MIDI range events and which will be as fast as Allegro and as good as Euterpe X Large:

https://github.com/asigalov61/Pentagram-Music-Transformer

Alex

**Comment by fakerybakery** [comment]
Ok, thanks! I'll check out the other repository!
